/**
 * Static filter options generated from database.
 * Generated on: Wed Jan 21 10:07:07 PST 2026
 */

/**
 * Category to Commodities mapping for instant local validation.
 * Used to immediately clear invalid child filters when parent category changes.
 */
export const CATEGORY_COMMODITIES = {
    "Fruits": [
        "Apple Pears", "Apples", "Apples, Processed", "Apricots", "Avocados", "Bananas",
        "Blackberries", "Blood Orange", "Blueberries", "Cantaloupes", "Cherries", 
        "Clementines", "Coconut", "Cranberries", "Currants", "Dekopon (Shiranui)",
        "Grapefruit", "Grapes", "Honeydews", "Kiwifruit", "Lemons", "Limes", "Mangoes",
        "Melogold", "Melon, Hami", "Meyer Lemon", "Nectarines", "Oranges", "Papaya",
        "Peaches", "Pears", "Persimmons", "Pineapples", "Plantains", "Plums", 
        "Pomegranates", "Pummelo", "Raspberries", "Rhubarb", "Satsuma", "Satsumas",
        "Strawberries", "Tangelos", "Tangerines", "Tangerines/Mandarins", "Watermelons"
    ],
    "Nuts": [
        "Almonds", "Filberts", "Peanuts", "Walnuts"
    ],
    "Vegetables": [
        "Aloe Leaves", "Anaheim Pepper", "Anise", "Artichokes", "Asparagus", "Basil",
        "Bay Leaves", "Bean Sprouts", "Beans", "Beans, Dragon Tongue", "Beans, Fava",
        "Beans, Haricot Vert (French Type)", "Beans, Italian Type", "Beans, Round Green Type",
        "Beans, Wax Type", "Beets", "Bok Choy", "Broccoli", "Brussels Sprouts", "Cabbage",
        "Cactus Leaf (Nopales)", "Carrots", "Cauliflower", "Celeriac (Celery Root)", "Celery",
        "Chayote", "Chervil", "Chinese Cabbage", "Chives", "Cilantro", "Collards",
        "Corn, Sweet", "Corn-Sweet", "Cucumbers", "Curly Parsley", "Dill", "Eggplant",
        "Endive", "Epasote (Epazote)", "Escarole", "Fenugreek (Methi)", "Garlic",
        "Ginger Root", "Greens, Broccoli Rabe (Rappini)", "Greens, Collard", 
        "Greens, Dandelion", "Greens, Kale", "Greens, Mustard", "Greens, Swiss Chard",
        "Horseradish", "Jalapeno Peppers", "Jerusalem Artichokes", "Jicama", "Kale",
        "Leeks", "Lettuce", "Lettuce, Boston", "Lettuce, Green Leaf", "Lettuce, Iceberg",
        "Lettuce, Red Leaf", "Lettuce, Romaine", "Marjoram", "Mint", "Mixed Mini Sweet Peppers",
        "Mushrooms", "Mustard", "Okra", "Onions, Green", "Oregano", "Parsley", "Parsnips",
        "Peas, English", "Peas, Snow", "Peas, Sugar Snap", "Peppers (Bell Type)",
        "Peppers, Anaheim", "Peppers, Bell Type", "Peppers, Fresno", "Peppers, Habanero",
        "Peppers, Jalapeno", "Peppers, Manzano", "Peppers, Mixed Mini Sweet Types",
        "Peppers, Pasilla", "Peppers, Serrano", "Peppers, Shishito", "Peppers, Yellow Chile",
        "Plain Parsley", "Poblano Pepper", "Radicchio", "Radishes", "Rapini/Broccoli Rabe",
        "Rosemary", "Rutabagas", "Sage", "Salad (Mixed Types)", "Salicornia (Sea Bean)",
        "Salsify", "Savory", "Serrano Peppers", "Snow Peas", "Sorrel", "Spinach", "Squash",
        "Squash, Acorn", "Squash, Banana", "Squash, Butternut", "Squash, Delicata",
        "Squash, Grey", "Squash, Kabocha", "Squash, Red Kuri", "Squash, Spaghetti",
        "Squash, Yellow Straightneck", "Squash, Zucchini", "Sugar Snap Peas", "Swiss Chard",
        "Tarragon", "Thyme", "Tomatillos", "Tomatoes", "Tomatoes, Cherry", 
        "Tomatoes, Grape Type", "Tomatoes, Plum Type", "Turmeric", "Turnip Tops", "Turnips",
        "Verdolaga", "Watercress", "Yuca (Cassava)"
    ],
    "Potatoes & Onions": [
        "Onions, Dry", "Potatoes", "Sweet Potatoes"
    ],
    "Other": [
        "Hemp (Seed) Oil", "Hemp Protein", "Hemp Seeds Shelled", "Honey", "Ornamentals"
    ]
};

/**
 * Reverse lookup: Commodity to Category mapping.
 * Built automatically from CATEGORY_COMMODITIES.
 */
export const COMMODITY_TO_CATEGORY = {};
Object.entries(CATEGORY_COMMODITIES).forEach(([category, commodities]) => {
    commodities.forEach(commodity => {
        COMMODITY_TO_CATEGORY[commodity] = category;
    });
});

export const STATIC_FILTERS = {
    "categories": [
        "Fruits",
        "Nuts",
        "Other",
        "Potatoes & Onions",
        "Vegetables"
    ],
    "commodities": [
        "Almonds",
        "Aloe Leaves",
        "Anaheim Pepper",
        "Anise",
        "Apple Pears",
        "Apples",
        "Apples, Processed",
        "Apricots",
        "Artichokes",
        "Asparagus",
        "Avocados",
        "Bananas",
        "Basil",
        "Bay Leaves",
        "Bean Sprouts",
        "Beans",
        "Beans, Dragon Tongue",
        "Beans, Fava",
        "Beans, Haricot Vert (French Type)",
        "Beans, Italian Type",
        "Beans, Round Green Type",
        "Beans, Wax Type",
        "Beets",
        "Blackberries",
        "Blood Orange",
        "Blueberries",
        "Bok Choy",
        "Broccoli",
        "Brussels Sprouts",
        "Cabbage",
        "Cactus Leaf (Nopales)",
        "Cantaloupes",
        "Carrots",
        "Cauliflower",
        "Celeriac (Celery Root)",
        "Celery",
        "Chayote",
        "Cherries",
        "Chervil",
        "Chinese Cabbage",
        "Chives",
        "Cilantro",
        "Clementines",
        "Coconut",
        "Collards",
        "Corn, Sweet",
        "Corn-Sweet",
        "Cranberries",
        "Cucumbers",
        "Curly Parsley",
        "Currants",
        "Dekopon (Shiranui)",
        "Dill",
        "Eggplant",
        "Endive",
        "Epasote (Epazote)",
        "Escarole",
        "Fenugreek (Methi)",
        "Filberts",
        "Garlic",
        "Ginger Root",
        "Grapefruit",
        "Grapes",
        "Greens, Broccoli Rabe (Rappini)",
        "Greens, Collard",
        "Greens, Dandelion",
        "Greens, Kale",
        "Greens, Mustard",
        "Greens, Swiss Chard",
        "Hemp (Seed) Oil",
        "Hemp Protein",
        "Hemp Seeds Shelled",
        "Honey",
        "Honeydews",
        "Horseradish",
        "Jalapeno Peppers",
        "Jerusalem Artichokes",
        "Jicama",
        "Kale",
        "Kiwifruit",
        "Leeks",
        "Lemons",
        "Lettuce",
        "Lettuce, Boston",
        "Lettuce, Green Leaf",
        "Lettuce, Iceberg",
        "Lettuce, Red Leaf",
        "Lettuce, Romaine",
        "Limes",
        "Mangoes",
        "Marjoram",
        "Melogold",
        "Melon, Hami",
        "Meyer Lemon",
        "Mint",
        "Mixed Mini Sweet Peppers",
        "Mushrooms",
        "Mustard",
        "Nectarines",
        "Okra",
        "Onions, Dry",
        "Onions, Green",
        "Oranges",
        "Oregano",
        "Ornamentals",
        "Papaya",
        "Parsley",
        "Parsnips",
        "Peaches",
        "Peanuts",
        "Pears",
        "Peas, English",
        "Peas, Snow",
        "Peas, Sugar Snap",
        "Peppers (Bell Type)",
        "Peppers, Anaheim",
        "Peppers, Bell Type",
        "Peppers, Fresno",
        "Peppers, Habanero",
        "Peppers, Jalapeno",
        "Peppers, Manzano",
        "Peppers, Mixed Mini Sweet Types",
        "Peppers, Pasilla",
        "Peppers, Serrano",
        "Peppers, Shishito",
        "Peppers, Yellow Chile",
        "Persimmons",
        "Pineapples",
        "Plain Parsley",
        "Plantains",
        "Plums",
        "Poblano Pepper",
        "Pomegranates",
        "Potatoes",
        "Pummelo",
        "Radicchio",
        "Radishes",
        "Rapini/Broccoli Rabe",
        "Raspberries",
        "Rhubarb",
        "Rosemary",
        "Rutabagas",
        "Sage",
        "Salad (Mixed Types)",
        "Salicornia (Sea Bean)",
        "Salsify",
        "Satsuma",
        "Satsumas",
        "Savory",
        "Serrano Peppers",
        "Snow Peas",
        "Sorrel",
        "Spinach",
        "Squash",
        "Squash, Acorn",
        "Squash, Banana",
        "Squash, Butternut",
        "Squash, Delicata",
        "Squash, Grey",
        "Squash, Kabocha",
        "Squash, Red Kuri",
        "Squash, Spaghetti",
        "Squash, Yellow Straightneck",
        "Squash, Zucchini",
        "Strawberries",
        "Sugar Snap Peas",
        "Sweet Potatoes",
        "Swiss Chard",
        "Tangelos",
        "Tangerines",
        "Tangerines/Mandarins",
        "Tarragon",
        "Thyme",
        "Tomatillos",
        "Tomatoes",
        "Tomatoes, Cherry",
        "Tomatoes, Grape Type",
        "Tomatoes, Plum Type",
        "Turmeric",
        "Turnip Tops",
        "Turnips",
        "Verdolaga",
        "Walnuts",
        "Watercress",
        "Watermelons",
        "Yuca (Cassava)"
    ],
    "varieties": [
        "AMBROSIA",
        "ASSORTED COLORS",
        "AUTUMN KING",
        "Acorn",
        "BABY",
        "BABY BOK CHOY",
        "BABY HYBRID TYPE",
        "BABY PEELED",
        "BARTLETT",
        "BEECH (HONSHIMEJI)",
        "BLACK SEEDLESS",
        "BLACK VARIETIES",
        "BOSC",
        "BRAEBURN",
        "BULB TYPE",
        "BURRO",
        "Baby Peeled Type Marked Small",
        "Baby Peeled Type Mixed Color",
        "Blood Orange",
        "Boston",
        "Buttercup",
        "Butternut",
        "CASTELFRANCO",
        "CHANTERELLE",
        "CHINESE",
        "COMICE",
        "CORTLAND",
        "COSMIC CRISP",
        "CREMINI",
        "CROWN CUT",
        "CURLY",
        "Cherry Type",
        "Chrysanthemums",
        "D'ANJOU",
        "DAISY",
        "DECALYXED",
        "EARLY FOOTHILL",
        "EARLY WONDERFUL",
        "ELEPHANT",
        "EMPIRE",
        "Envy",
        "FINGERLING",
        "FLAT",
        "FLAT TYPE",
        "FORELLE",
        "FUJI",
        "FUYU",
        "GALA",
        "GARNET",
        "GINGER GOLD",
        "GLOBE",
        "GOLDEN (HWANGKEUM)",
        "GOLDEN DELICIOUS",
        "GRANNY SMITH",
        "GRAPE TYPE",
        "GREEN",
        "GREY",
        "Gala/Royal Gala",
        "Green Leaf",
        "HACHIYA",
        "HADEN",
        "HANNA",
        "HASS",
        "HAYWARD",
        "HEARTS",
        "HEIRLOOM VARIETIES",
        "HEN OF THE WOODS",
        "HONEY",
        "HONEYCRISP",
        "Hass-Marked Extra Large",
        "Hass-Marked Large",
        "Hass-Marked Medium",
        "Hass-Marked Small",
        "INDIAN",
        "Iceberg",
        "JAPANESE TYPES",
        "JEWELS",
        "JONAGOLD",
        "JONATHAN",
        "JUICE",
        "JUICE MARKED CIDER",
        "JUICE TYPE",
        "KENT",
        "KING OYSTER",
        "Kabocha",
        "LACINATO (TUSCAN)",
        "LONG SEEDLESS",
        "LONG WHITE",
        "MANZANO",
        "MARADOL TYPE",
        "MARADOL/TAINUNG TYPES",
        "MARKED RIO STAR",
        "MCINTOSH",
        "MILPERO",
        "MIXED COLORS",
        "MORELS",
        "Meyer",
        "NAPA",
        "NAVEL",
        "Navel, Cara Cara",
        "OPAL",
        "ORANGE",
        "ORANGE TYPE",
        "ORANGE TYPES",
        "OYSTER",
        "PEAR TYPE",
        "PEERLESS",
        "PERSIAN",
        "PICKLE",
        "PINK LADY/CRIPPS PINK",
        "PLAIN",
        "PORTOBELLA",
        "PRICKLY TYPE",
        "PURPLE TOP",
        "PURPLE TYPE",
        "Plum Type (Roma)",
        "Poinsettias",
        "RAINIER",
        "RED",
        "RED DELICIOUS",
        "RED FLESH SEEDED TYPE",
        "RED FLESH SEEDLESS MINIATURE",
        "RED FLESH SEEDLESS TYPE",
        "RED GLOBE",
        "RED SEEDLESS",
        "RED TYPE",
        "RED TYPES",
        "RED VARIETIES",
        "RICH LADY",
        "ROMA",
        "ROUND GREEN TYPE",
        "ROUND RED",
        "ROUND WHITE",
        "RUSSET",
        "Red Globe Seeded Type",
        "Red Leaf",
        "Romaine",
        "Romaine (Hearts)",
        "Rose, Hybrid Tea",
        "Round Varieties",
        "Round Varieties Marked Extra Large",
        "Round Varieties Marked Large",
        "SAVOY TYPE",
        "SEEDLESS TYPE",
        "SHIITAKE",
        "SHINKO",
        "SOLO TYPE",
        "Spaghetti",
        "Spring Mix",
        "TANGO",
        "THAI",
        "TOMMY ATKINS",
        "TREVISO",
        "Tulips",
        "VALENCIA",
        "VARIOUS BLACK VAREIETIES",
        "VARIOUS GREENSKIN VARIETIES",
        "VARIOUS VARIETIES",
        "VARIOUS WHITE FLESH VARIETIES",
        "VARIOUS YELLOW FLESH VARIETIES",
        "VINE RIPE - HEIRLOOM VARIETIES",
        "VINE RIPE - ON THE VINE",
        "VINE RIPES",
        "VINE RIPES - ON THE VINE",
        "VIRGINIA",
        "Various Greenskin Marked Extra Large",
        "Vine Ripes - Heirloom Varieties",
        "W. MURCOTT AFOURER",
        "WHITE",
        "WHITE SEEDLESS TYPE",
        "WHITE TYPES",
        "WITH STEMS",
        "WITLOOF",
        "WOODEAR",
        "YELLOW",
        "YELLOW FLESH",
        "YELLOW MARKED SWEET",
        "YELLOW TYPE",
        "YOUNG TYPE",
        "Yellow Crookneck/Straightneck",
        "Zucchini"
    ],
    "packages": [
        "1 1/9 bushel cartons",
        "1 1/9 bushel cartons/crates",
        "1 bu, 1 1/9 bu, 1 1/6 bu cartons wrapped",
        "1 layer containers",
        "1 lb bag",
        "1 lb film bags",
        "1 lb film bags loose",
        "1 lb package",
        "1 pint (11-12 oz cntr w/ lid)",
        "1 pint package",
        "1 pound bags",
        "1-1.5 lb bags",
        "1-lb containers with lids",
        "1/2 bushel cartons",
        "1/2 cartons",
        "10 kg cartons",
        "10 kg containers",
        "10 kg containers loose",
        "10 kg crates",
        "10 kg mesh sacks",
        "10 lb bag",
        "10 lb cartons",
        "10 lb film bags",
        "10 lb reusable plastic containers (RPC)",
        "10 oz",
        "10 oz package",
        "10-12 oz package",
        "11 lb cartons bunched",
        "11 oz package",
        "12 oz",
        "12 oz bag",
        "12 oz package",
        "12 oz tray wrapped",
        "12-14 oz trays filmwrapped",
        "128 oz (1 gallon)",
        "15 lb bag",
        "15 lb cartons",
        "16 kg cartons",
        "16 oz",
        "16 oz bag",
        "17 kg containers",
        "18 lb containers bagged",
        "18 oz package",
        "19 lb lugs bagged",
        "2 count",
        "2 lb bag",
        "2 lb container with lid",
        "2 lb package",
        "2 pound bags",
        "2-lb containers with lids",
        "2/3 cartons",
        "2/5 bushel cartons wrapped",
        "20 lb cartons",
        "20 lb cartons loose",
        "20 lb containers",
        "20 lb film bags",
        "20 lb film bags loose",
        "22 lb cartons",
        "24 inch bins",
        "24 oz",
        "24 oz bag",
        "25 lb cartons",
        "25 lb cartons loose",
        "25 lb cartons place pack",
        "25 lb film bags",
        "25 lb film bags topped",
        "25 lb sacks",
        "25 lb sacks loose",
        "3 count",
        "3 count filmbag",
        "3 count mesh bags",
        "3 lb bag",
        "3 lb bags",
        "30 lb cartons",
        "30 lb mesh sacks",
        "30 lb reusable plastic containers (RPC)",
        "30-35 lb cartons",
        "32 oz",
        "32 oz bag",
        "35 lb containers",
        "35 lb crates",
        "38 lb reusable plastic containers (RPC)",
        "38-40 lb containers",
        "4 Inch Pot",
        "4 count mesh bags",
        "4 lb bag",
        "4 lb film bags",
        "4 oz",
        "4 oz containers with lid",
        "4/5 bushel cartons wrapped",
        "4/7 bushel cartons",
        "40 lb cartons",
        "40 lb cartons containerized",
        "40 lb containers",
        "45 lb cartons",
        "5 count mesh bags",
        "5 kg cartons bagged",
        "5 kg containers",
        "5 kg/11 lb cartons",
        "5 kg/11 lb flats",
        "5 lb bag",
        "5 lb cartons",
        "5 lb film bag",
        "5 lb film bags",
        "5 lb package",
        "5-6 ct trays filmwrapped",
        "5-7 oz package",
        "5-9 oz package",
        "5.6-6 oz package",
        "50 lb cartons",
        "50 lb sacks",
        "50 lb sacks loose",
        "6 inch pot",
        "6 kg containers",
        "6 oz bags",
        "6 oz package",
        "6-oz film bags",
        "64 oz (1/2 gallon)",
        "7 oz",
        "7/10 bushel cartons",
        "8 Inch Pot",
        "8 lb bag",
        "8 lb cartons",
        "8 lb film bags",
        "8 oz",
        "8 oz bags",
        "8 oz package",
        "8-10 oz package",
        "8-9 kg containers",
        "9 kg (19.8 lb) containers",
        "9 kg (19.8 lb) containers loose",
        "9 kg containers",
        "9.8 oz package",
        "96 oz (3/4 gallon)",
        "baled 10 5-lb film bags",
        "baled 5 10-lb film bags",
        "bins",
        "bunched 10s",
        "bunched 12s",
        "bunched 15s",
        "bunched 5s",
        "bunched 7s",
        "bushel & 40-45 lb reusable plastic containers (RPC)",
        "bushel cartons/crates",
        "cartons",
        "cartons 1 layer",
        "cartons 1 layer tray pack",
        "cartons 10 1-lb film bags",
        "cartons 10 3-lb mesh bags",
        "cartons 12 1-lb film bags",
        "cartons 12 10-oz cups with lids",
        "cartons 12 18-oz containers with lids",
        "cartons 12 3-count packages",
        "cartons 12 3-lb film bags",
        "cartons 12 8-oz trays film wrapped",
        "cartons 2 layer",
        "cartons 2 layer tray pack",
        "cartons 24 3 1/2-oz film bags",
        "cartons 30 1-lb film bags",
        "cartons 4 film bags iceless",
        "cartons bunched",
        "cartons film lined",
        "cartons film wrapped",
        "cartons topped 30 6-oz film bags",
        "cartons tray pack",
        "cartons/crates",
        "crates bunched",
        "each",
        "film bags bunched",
        "flat cartons",
        "flats 1 layer",
        "flats 12 1-pint baskets",
        "flats 12 1-pint cups with lids",
        "flats 12 1/2-pint cups with lids",
        "flats 12 10-oz containers with lids",
        "flats 12 6-oz cups with lids",
        "flats 12 6.2-oz cups",
        "flats 4 1-lb containers with lids",
        "flats 4 2-lb containers with lids",
        "flats 8 1-lb containers with lids",
        "lugs",
        "oversized 1/2 cartons",
        "oversized 2/3 cartons",
        "per bunch",
        "per lb",
        "per package",
        "per sleeve",
        "sacks 10 5-lb film bags",
        "sacks 24 2-lb film bags",
        "sacks 48 1-lb film bags",
        "trays 4-5 ears film wrapped"
    ],
    "districts": [
        "ATWATER LIVINGSTON CALIFORNIA",
        "BAJA CALIFORNIA",
        "BAJA DISTRICT",
        "BRITISH COLUMBIA",
        "CENTRAL COAST CALIFORNIA",
        "CENTRAL SAN JOAQUIN VALLEY CALIFORNIA",
        "DESERT DISTRICT CALIFORNIA",
        "KERN DISTRICT CALIFORNIA",
        "MEXICO CROSSINGS THROUGH ARIZONA, CALIFORNIA AND TEXAS",
        "MEXICO CROSSINGS THROUGH OTAY MESA CALIFORNIA",
        "MEXICO CROSSINGS THROUGH TEXAS",
        "OXNARD DISTRICT CALIFORNIA",
        "SAN JOAQUIN VALLEY CALIFORNIA",
        "SANTA MARIA CALIFORNIA",
        "SOUTH AND CENTRAL DISTRICT CALIFORNIA",
        "SOUTHERN CALIFORNIA COAST AND MEXICO CROSSINGS THROUGH OTAY MESA CALIFORNIA"
    ],
    "organics": [
        "N",
        "No",
        "Y",
        "Yes"
    ]
};
